# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import externalParameter.labbricksproto_pb2 as labbricksproto__pb2


class LabbricksStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DeviceInfo = channel.unary_stream(
        '/labbricksproto.Labbricks/DeviceInfo',
        request_serializer=labbricksproto__pb2.DeviceRequest.SerializeToString,
        response_deserializer=labbricksproto__pb2.DeviceInfoMsg.FromString,
        )
    self.DeviceState = channel.unary_stream(
        '/labbricksproto.Labbricks/DeviceState',
        request_serializer=labbricksproto__pb2.DeviceRequest.SerializeToString,
        response_deserializer=labbricksproto__pb2.DeviceStateMsg.FromString,
        )
    self.SetFrequency = channel.unary_unary(
        '/labbricksproto.Labbricks/SetFrequency',
        request_serializer=labbricksproto__pb2.DeviceSetIntRequest.SerializeToString,
        response_deserializer=labbricksproto__pb2.DeviceStateMsg.FromString,
        )
    self.SetPower = channel.unary_unary(
        '/labbricksproto.Labbricks/SetPower',
        request_serializer=labbricksproto__pb2.DeviceSetIntRequest.SerializeToString,
        response_deserializer=labbricksproto__pb2.DeviceStateMsg.FromString,
        )
    self.SetRFOn = channel.unary_unary(
        '/labbricksproto.Labbricks/SetRFOn',
        request_serializer=labbricksproto__pb2.DeviceSetBoolRequest.SerializeToString,
        response_deserializer=labbricksproto__pb2.DeviceStateMsg.FromString,
        )
    self.SetState = channel.unary_unary(
        '/labbricksproto.Labbricks/SetState',
        request_serializer=labbricksproto__pb2.DeviceSetStateRequest.SerializeToString,
        response_deserializer=labbricksproto__pb2.DeviceStateMsg.FromString,
        )
    self.UpdateDevices = channel.unary_stream(
        '/labbricksproto.Labbricks/UpdateDevices',
        request_serializer=labbricksproto__pb2.DeviceRequest.SerializeToString,
        response_deserializer=labbricksproto__pb2.DeviceInfoMsg.FromString,
        )
    self.DeviceNotifications = channel.unary_stream(
        '/labbricksproto.Labbricks/DeviceNotifications',
        request_serializer=labbricksproto__pb2.DeviceRequest.SerializeToString,
        response_deserializer=labbricksproto__pb2.DeviceStateMsg.FromString,
        )


class LabbricksServicer(object):
  """The greeting service definition.
  """

  def DeviceInfo(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeviceState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetFrequency(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPower(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetRFOn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateDevices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeviceNotifications(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LabbricksServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DeviceInfo': grpc.unary_stream_rpc_method_handler(
          servicer.DeviceInfo,
          request_deserializer=labbricksproto__pb2.DeviceRequest.FromString,
          response_serializer=labbricksproto__pb2.DeviceInfoMsg.SerializeToString,
      ),
      'DeviceState': grpc.unary_stream_rpc_method_handler(
          servicer.DeviceState,
          request_deserializer=labbricksproto__pb2.DeviceRequest.FromString,
          response_serializer=labbricksproto__pb2.DeviceStateMsg.SerializeToString,
      ),
      'SetFrequency': grpc.unary_unary_rpc_method_handler(
          servicer.SetFrequency,
          request_deserializer=labbricksproto__pb2.DeviceSetIntRequest.FromString,
          response_serializer=labbricksproto__pb2.DeviceStateMsg.SerializeToString,
      ),
      'SetPower': grpc.unary_unary_rpc_method_handler(
          servicer.SetPower,
          request_deserializer=labbricksproto__pb2.DeviceSetIntRequest.FromString,
          response_serializer=labbricksproto__pb2.DeviceStateMsg.SerializeToString,
      ),
      'SetRFOn': grpc.unary_unary_rpc_method_handler(
          servicer.SetRFOn,
          request_deserializer=labbricksproto__pb2.DeviceSetBoolRequest.FromString,
          response_serializer=labbricksproto__pb2.DeviceStateMsg.SerializeToString,
      ),
      'SetState': grpc.unary_unary_rpc_method_handler(
          servicer.SetState,
          request_deserializer=labbricksproto__pb2.DeviceSetStateRequest.FromString,
          response_serializer=labbricksproto__pb2.DeviceStateMsg.SerializeToString,
      ),
      'UpdateDevices': grpc.unary_stream_rpc_method_handler(
          servicer.UpdateDevices,
          request_deserializer=labbricksproto__pb2.DeviceRequest.FromString,
          response_serializer=labbricksproto__pb2.DeviceInfoMsg.SerializeToString,
      ),
      'DeviceNotifications': grpc.unary_stream_rpc_method_handler(
          servicer.DeviceNotifications,
          request_deserializer=labbricksproto__pb2.DeviceRequest.FromString,
          response_serializer=labbricksproto__pb2.DeviceStateMsg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'labbricksproto.Labbricks', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
